"""new fields in user model

Revision ID: 0dddb1f1b1eb
Revises: d24a15323f90
Create Date: 2020-06-26 11:20:04.560276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dddb1f1b1eb'
down_revision = 'd24a15323f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number_of_questions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number_of_questions')
    # ### end Alembic commands ###
