"""empty message

Revision ID: 8f77da67ace2
Revises: 0dddb1f1b1eb
Create Date: 2020-06-26 12:04:33.114254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f77da67ace2'
down_revision = '0dddb1f1b1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number_of_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number_of_questions')
    # ### end Alembic commands ###
